const keyMap = {
  c: 'clear',
  C: 'clear',
  Escape: 'clear',
  a: 'ans',
  A: 'ans',
  e: 'entry',
  E: 'entry',
  x: 'multiply',
  X: 'multiply',
  Backspace: 'delete',
  Delete: 'delete',
  '(': 'open-paren',
  ')': 'close-paren',
  '/': 'divide',
  '*': 'multiply',
  '-': 'subtract',
  '+': 'add',
  Enter: 'equals',
  '=': 'equals',
  '.': 'decimal',
  _: 'negative',
  0: 'zero',
  1: 'one',
  2: 'two',
  3: 'three',
  4: 'four',
  5: 'five',
  6: 'six',
  7: 'seven',
  8: 'eight',
  9: 'nine'
};

export default keyMap;
